LEVEL1 = """
WWWWWWWWWWWWWWWWWWWWWWWWWW
WPW   W          W      WW
W WWW W W WWWWWW W WW W WW
W     WWW WW   W W  W W WW
W WWW        WWWWWW W W WW
W W W WWWW W W    WWW WWWW
W W W W  W W WW W W     WW
W W W   WW W WWWW WWW WWWW
W W WWWWWW W            WW
W     W  W WWWWWWWWWWWW WW
WWW WWWW  WW WW   W   W WW
W W      WW     W W W W WW
W W WWWWWW  WWWWW W WWW WW
W W W      W W W        WW
W WWW W WWW  W    WWW W WW
W W W W W W WWWWWWW W W WW
W     W   W       W   W WW
WWWWWWWWW W WWWWW WWWWWWWW
W W       W W W W       WW
W W WWWWWWW   W  WWWW W WW
W W W   W W W W W W W W WW
W W W W W   W     W   W WW
W W WWW W WWWW WWWWWWWW WW
W         W            EWW
WWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWW
"""

LEVEL2 = """
WWWWWWWWWWWWWWWWWWWWWWWWWW
WPW   W          W      WW
W WWW W W WWWWWW W WW W WW
W     WWW WW   W W  W W WW
W WWW        WWWWWW W W WW
W W W WWWW W W    WWW WWWW
W W W W  W W WW W W     WW
W W W   WW W WWWW WWW WWWW
W W WWWWWW W            WW
W     W  W WWWWWWWWWWWW WW
WWW WWWW  WW WW   W   W WW
W W      WW     W W W W WW
W W WWWWWW  WWWWW W WWW WW
W W W      W W W        WW
W WWW W WWW  W    WWW W WW
W W W W W W WWWWWWW W W WW
W     W   W       W   W WW
WWWWWWWWW W WWWWW WWWWWEWW
W W       W W W W       WW
W W WWWWWWW   W  WWWW W WW
W W W   W W W W W W W W WW
W W W W W   W     W   W WW
W W WWW W WWWW WWWWWWWW WW
W         W        W    WW
WWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWW
"""

LEVEL3 = """
WWWWWWWWWWWWWWWWWWWWWWWWWW
WPW   W          W      WW
W WWW W W WWWWWW W WW W WW
W     WWW WW   W W  W W WW
W WWW        WWWWWW W W WW
W W W WWWW W     EWWW WWWW
W W W W  W W WW W W     WW
W W W   WW W WWWW WWW WWWW
W W WWWWWW W            WW
W     W  W WWWWWWWWWWWW WW
WWW WWWW  WW WW   W   W WW
W W      WW     W W W W WW
W WWWWWWWW  WWWWW W WWW WW
W W W      W W W        WW
W W W W WWW  W    WWW W WW
W W W W W W WWWWWWW W W WW
W     W   W       W   W WW
WWWWWWWWW W WWWWW WWWWWWWW
W W       W W W W       WW
W W WWWWWWW   W  WWWW W WW
W W W   W W W W W W W W WW
W W W W W   W     W   W WW
W W WWW W WWWW WWWWWWWW WW
W         W        W    WW
WWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWW
"""

LEVEL4 = """
WWWWWWWWWWWWWWWWWWWWWWWWWW
WPW   W          W      WW
W WWW W W WWWWWW W WW W WW
W     WWW WW   W W  W W WW
W WWW        WWWWWW W WEWW
W W W WWWW W W    WWW WWWW
W W W W  W W WW W W     WW
W W W   WW W WWWW WWW WWWW
W W WWWWWW W            WW
W     W  W WWWWWWWWWWWW WW
WWW WWWW  EW WW   W   W WW
W W      WW     W W W W WW
W W WWWWWW  WWWWW W WWW WW
W W W      W W W        WW
W WWW W WWW  W    WWW W WW
W W W W W W WWWWWWW W W WW
W     W   W       W   W WW
WWWWWWWWW W WWWWW WWWWWWWW
W W       W W W W       WW
W W WWWWWWW   W  WWWW W WW
W W W   W W W W W W W W WW
W W W W W   W     W   W WW
W W WWW W WWWW WWWWWWWW WW
W         W        W    WW
WWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWW
"""

LEVEL5 = """
WWWWWWWWWWWWWWWWWWWWWWWWWW
WPW   W          W      WW
W WWW W W WWWWWW W WW W WW
W     WWW WW   W W  W W WW
W WWW        WWWWWW W W WW
W W W WWWW W W    WWW WWWW
W W W W  W W WW W W     WW
W W W   WW W WWWW WWW WWWW
W W WWWWWW W            WW
W     W  W WWWWWWWWWWWW WW
WWW WWWW  WW WW   W   W WW
W W      WW     W W W W WW
W W WWWWWW  WWWWW W WWW WW
W W W      W W W        WW
W WWW W WWW  W    WWW W WW
W W W W W W WWWWW W W W WW
W     W   W       W   W WW
WWWWWWWWW W WWWWWWWWWWWWWW
W W       W W W W       WW
W W WWW WWW   W  WWWW W WW
W W W   W W W W W W W W WW
W W WEW W   W     W   W WW
W W WWW W WWWW WWWWWWWW WW
W         W        W    WW
WWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWW
"""